//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splicer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Splicer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Input.
        /// </summary>
        internal static string AudioInputPinNamePrefix {
            get {
                return ResourceManager.GetString("AudioInputPinNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASF Writer.
        /// </summary>
        internal static string DefaultAsfWriterName {
            get {
                return ResourceManager.GetString("DefaultAsfWriterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File.
        /// </summary>
        internal static string DefaultFileDestinationName {
            get {
                return ResourceManager.GetString("DefaultFileDestinationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null Renderer.
        /// </summary>
        internal static string DefaultNullRendererName {
            get {
                return ResourceManager.GetString("DefaultNullRendererName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Rendering Window.
        /// </summary>
        internal static string DefaultVideoRenderingWindowCaption {
            get {
                return ResourceManager.GetString("DefaultVideoRenderingWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wav DEST.
        /// </summary>
        internal static string DefaultWavDestinationName {
            get {
                return ResourceManager.GetString("DefaultWavDestinationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied async result was not issued by this instance.
        /// </summary>
        internal static string ErrorAsyncResultNotIssuesByThisInstance {
            get {
                return ResourceManager.GetString("ErrorAsyncResultNotIssuesByThisInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not cancel this renderer, it is already completing/canceling.
        /// </summary>
        internal static string ErrorAttemptToCancelWhenCancelingOrCompleting {
            get {
                return ResourceManager.GetString("ErrorAttemptToCancelWhenCancelingOrCompleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not cancel, a request to cancel has already been issued - have you remembered to call EndCancel?.
        /// </summary>
        internal static string ErrorAttemptToCancelWhenCancelInProgress {
            get {
                return ResourceManager.GetString("ErrorAttemptToCancelWhenCancelInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not render to AVI when no video group exists.
        /// </summary>
        internal static string ErrorCanNotRenderAviWhenNoVideoGroupExists {
            get {
                return ResourceManager.GetString("ErrorCanNotRenderAviWhenNoVideoGroupExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not resolve media type for encoder ({0} khz, {1} kbps, mono? {2}) - list of available formats follow:.
        /// </summary>
        internal static string ErrorCanNotResolveMediaTypeForEncoder {
            get {
                return ResourceManager.GetString("ErrorCanNotResolveMediaTypeForEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not resolve audio encoder &quot;{0}&quot;.
        /// </summary>
        internal static string ErrorCanResolveAudioEncoder {
            get {
                return ResourceManager.GetString("ErrorCanResolveAudioEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not add audio clips to a track which exists within a non-audio group.
        /// </summary>
        internal static string ErrorCantAddAudioClipsToVideoGroup {
            get {
                return ResourceManager.GetString("ErrorCantAddAudioClipsToVideoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not add video or image clips to a track which exists within a non-video group.
        /// </summary>
        internal static string ErrorCantAddVideoClipsToAudioGroup {
            get {
                return ResourceManager.GetString("ErrorCantAddVideoClipsToAudioGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndCancel has already been called fo this async result.
        /// </summary>
        internal static string ErrorEndCancelAlreadyCalledForAsyncResult {
            get {
                return ResourceManager.GetString("ErrorEndCancelAlreadyCalledForAsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndRender has already been called for this async result.
        /// </summary>
        internal static string ErrorEndRenderAlreadyCalledForAsyncResult {
            get {
                return ResourceManager.GetString("ErrorEndRenderAlreadyCalledForAsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred while attempting to cancel render request, see inner exception for details.
        /// </summary>
        internal static string ErrorExceptionOccuredDuringCancelRenderRequest {
            get {
                return ResourceManager.GetString("ErrorExceptionOccuredDuringCancelRenderRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred while attempting to render, see inner exception for details.
        /// </summary>
        internal static string ErrorExceptionOccuredDuringRenderRequest {
            get {
                return ResourceManager.GetString("ErrorExceptionOccuredDuringRenderRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames per second must be greater then 0.
        /// </summary>
        internal static string ErrorFramesPerSecondMustBeGreaterThenZero {
            get {
                return ResourceManager.GetString("ErrorFramesPerSecondMustBeGreaterThenZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph not yet started.
        /// </summary>
        internal static string ErrorGraphNotYetStarted {
            get {
                return ResourceManager.GetString("ErrorGraphNotYetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups are top level timeline components and do not support this property.
        /// </summary>
        internal static string ErrorGroupsDontSupportContainerProperty {
            get {
                return ResourceManager.GetString("ErrorGroupsDontSupportContainerProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length specified.
        /// </summary>
        internal static string ErrorInvalidLengthSpecified {
            get {
                return ResourceManager.GetString("ErrorInvalidLengthSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file name is null or invalid.
        /// </summary>
        internal static string ErrorInvalidOutputFileName {
            get {
                return ResourceManager.GetString("ErrorInvalidOutputFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must call BeginCancel before EndCancel.
        /// </summary>
        internal static string ErrorMustCallBeginCancelBeforeEndCancel {
            get {
                return ResourceManager.GetString("ErrorMustCallBeginCancelBeforeEndCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must call BeginRender before EndRender.
        /// </summary>
        internal static string ErrorMustCallBeginRenderBeforeEndRender {
            get {
                return ResourceManager.GetString("ErrorMustCallBeginRenderBeforeEndRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio group to render.
        /// </summary>
        internal static string ErrorNoAudioStreamToRender {
            get {
                return ResourceManager.GetString("ErrorNoAudioStreamToRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No group found supporting a clip of type &quot;{0}&quot;.
        /// </summary>
        internal static string ErrorNoGroupForSupportingClipOfType {
            get {
                return ResourceManager.GetString("ErrorNoGroupForSupportingClipOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tracks found in the first group of type &quot;{0}&quot;.
        /// </summary>
        internal static string ErrorNoTracksFoundInFirstGroupOfType {
            get {
                return ResourceManager.GetString("ErrorNoTracksFoundInFirstGroupOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pins enumerator is null.
        /// </summary>
        internal static string ErrorPinsEnumeratorIsNull {
            get {
                return ResourceManager.GetString("ErrorPinsEnumeratorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A previous render request has not yet been completed - have you remembered to call EndRender?.
        /// </summary>
        internal static string ErrorPreviousRenderRequestInProgress {
            get {
                return ResourceManager.GetString("ErrorPreviousRenderRequestInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The render request was canceled by the user.
        /// </summary>
        internal static string ErrorRenderRequestCanceledByUser {
            get {
                return ResourceManager.GetString("ErrorRenderRequestCanceledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized bit format.
        /// </summary>
        internal static string ErrorUnrecognizedBitFormat {
            get {
                return ResourceManager.GetString("ErrorUnrecognizedBitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected windows media profile encodes audio information, yet no audio group exists.
        /// </summary>
        internal static string ErrorWMProfileRequiresAudioGroup {
            get {
                return ResourceManager.GetString("ErrorWMProfileRequiresAudioGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected windows media profile encodes video information, yet no video group exists.
        /// </summary>
        internal static string ErrorWMProfileRequiresVideoGroup {
            get {
                return ResourceManager.GetString("ErrorWMProfileRequiresVideoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frame{0}.jpg.
        /// </summary>
        internal static string ImagesToDiskParticipantFilenameTemplate {
            get {
                return ResourceManager.GetString("ImagesToDiskParticipantFilenameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Event Thread.
        /// </summary>
        internal static string MediaEventThreadName {
            get {
                return ResourceManager.GetString("MediaEventThreadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        internal static string Mono {
            get {
                return ResourceManager.GetString("Mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction: {0}, Name: {1}, QueryId: {2}.
        /// </summary>
        internal static string PinQueryInfoTemplate {
            get {
                return ResourceManager.GetString("PinQueryInfoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereo.
        /// </summary>
        internal static string Stereo {
            get {
                return ResourceManager.GetString("Stereo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to splicerTempAudio{0}{1}.
        /// </summary>
        internal static string TemporaryAudioFilenameTemplate {
            get {
                return ResourceManager.GetString("TemporaryAudioFilenameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to splicerTempImage{0}.bmp.
        /// </summary>
        internal static string TemporaryImageFilenameTemplate {
            get {
                return ResourceManager.GetString("TemporaryImageFilenameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported AMMEdiaType encountered.
        /// </summary>
        internal static string UnsupportedAMMEdiaType {
            get {
                return ResourceManager.GetString("UnsupportedAMMEdiaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Input.
        /// </summary>
        internal static string VideoInputPinNamePrefix {
            get {
                return ResourceManager.GetString("VideoInputPinNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;clip start=&quot;{0}&quot; stop=&quot;{1}&quot; src=&quot;{2}&quot; mstart=&quot;{3}&quot; /&gt;.
        /// </summary>
        internal static string VirtualClipToStringTemplate {
            get {
                return ResourceManager.GetString("VirtualClipToStringTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.000}s.
        /// </summary>
        internal static string WatermarkTimeStamp {
            get {
                return ResourceManager.GetString("WatermarkTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} kHz - {2} kbps.
        /// </summary>
        internal static string WavFormatInfoTemplate {
            get {
                return ResourceManager.GetString("WavFormatInfoTemplate", resourceCulture);
            }
        }
    }
}
